solana: adjustments to proposals
wormhole-foundation/example-liquidity-layer pull request #10
Opened 2024-03-14 20:03 UTC by deekerno

## Description
This PR makes a few adjustments to the proposals workflow.

## Testing Steps
Tests should pass.

2024-03-20 20:14 UTC, a5-pickle requested changes
@deekerno can you also fix the propose new auction parameters instruction to use `AdminCustodian`, too, since the custodian no longer has to be mutable?

2024-03-20 20:14 UTC, a5-pickle commented on solana/programs/matching-engine/src/processor/admin/update/auction_parameters.rs
>      owner: Signer<'info>,
Can you replace the `owner` and `custodian` to use this shared context instead? https://github.com/wormhole-foundation/example-liquidity-layer/blob/a17a2b545abaaa0a42db9c555f8d960147ac99fb/solana/programs/matching-engine/src/state/custodian.rs#L61

2024-03-20 20:16 UTC, a5-pickle commented on solana/programs/matching-engine/src/processor/admin/update/auction_parameters.rs
>      owner: Signer<'info>,
Sorry I meant this since the Custodian is mutable: https://github.com/wormhole-foundation/example-liquidity-layer/blob/a17a2b545abaaa0a42db9c555f8d960147ac99fb/solana/programs/matching-engine/src/state/custodian.rs#L69

2024-03-20 23:45 UTC, deekerno commented on solana/programs/matching-engine/src/processor/admin/update/auction_parameters.rs
>      owner: Signer<'info>,
@a5-pickle Addressed your feedback. For the `has_one` property in the macro, it seems that I'm unable to directly refer to `admin.owner`; so I added an equivalent key check assertion to the constraints. Let me know if that isn't the way to address that.

2024-03-21 00:44 UTC, a5-pickle requested changes

2024-03-21 00:44 UTC, a5-pickle commented on solana/programs/matching-engine/src/processor/admin/update/auction_parameters.rs
> +            require!(
`require_keys_eq!` would be nicer here because it'll show the key differences (actual vs expected) in the program logs.

2024-03-21 00:44 UTC, a5-pickle commented on solana/ts/tests/01__matchingEngine.ts
> +            it.skip("Cannot Update Auction Config (Auction Config Mismatch)", async function () {
Does this test need to be modified, or can we remove it?

2024-03-21 00:44 UTC, a5-pickle commented on solana/ts/tests/01__matchingEngine.ts
> +            // TODO: Is this necessary if we enact in the test above?
Any plans to use this? If not, let's remove it.

2024-03-21 15:49 UTC, a5-pickle approved these changes
Will fix reverting with a specific error on owner check in a subsequent PR.

2024-03-21 15:49 UTC, merged