solana: handle non-existent best offer token for settle complete
wormhole-foundation/example-liquidity-layer pull request #173
Opened 2024-05-31 19:28 UTC by a5-pickle

2024-06-06 19:48 UTC, mdulin2 approved these changes
This is a good find and fix. The ability for owners to open and close token accounts at will has been a source for bugs thus far. Would be wise to do a variant analysis for this.

2024-06-06 20:42 UTC, johnsaigle requested changes
Added a note about emitting events. I think we might be missing an instance where one should go out?

I found this code hard to reason about given that the variables `amount`  and `token` are used in different ways in different contexts. It's hard to track what these terms means especially that a lot of the logic is happening in a large `let-match` block.

Would you be able to rename the variables in some cases? e.g. change instances of `token` and `amount` to `executor_token` or `executor_amount` after you destructure the amounts in the `if let Some()` constructions.

Even though it adds some repetition and redundancy I think it's better for maintaining this code long-term.

2024-06-06 20:42 UTC, johnsaigle commented on solana/programs/matching-engine/src/processor/auction/settle/complete.rs
> +        emit!(crate::events::AuctionSettled {
Shouldn't we also emit an event in the case where all of the funds are sent to the executor?

2024-06-06 20:43 UTC, johnsaigle requested changes
~~Sorry meant for the previous review to be `Request Changes` not `Comment`~~
I don't have the ability to leave a Request Changes review on this repo 🙃

2024-06-06 22:06 UTC, a5-pickle commented on solana/programs/matching-engine/src/processor/auction/settle/complete.rs
> +        emit!(crate::events::AuctionSettled {
We could. I only added this event for the benefit of the auction participants. I don't think all auction participants (including executors/liquidators) benefit from this event; the best offer participant would so he can reconcile his own token balances.

@gator-boi what do you think?

2024-06-06 23:24 UTC, gator-boi commented on solana/programs/matching-engine/src/processor/auction/settle/complete.rs
> +        emit!(crate::events::AuctionSettled {
Let's add this event. Hopefully it will help the best offer participant in future cases.

2024-06-18 16:57 UTC, a5-pickle commented on solana/programs/matching-engine/src/processor/auction/settle/complete.rs
> +        emit!(crate::events::AuctionSettled {
Fixed the event here: https://github.com/wormhole-foundation/example-liquidity-layer/pull/173/commits/be3be926b2146fd31d15d624d3e1c720bb85969f. How does this look? It changed the schema for the event a bit. But it has more info now

2024-06-18 17:13 UTC, johnsaigle approved these changes
- Event added
- New variable names make the code easier to reason about imo

2024-06-18 17:19 UTC, gator-boi approved these changes

2024-06-18 17:20 UTC, merged