solana: some clean up
wormhole-foundation/example-liquidity-layer pull request #191
Opened 2024-07-10 21:19 UTC by a5-pickle

* Uptick solana to 1.18.15 and anchor to 0.30.1
* Add clippy.toml
* Set paused_set_by to owner on initialize

2024-07-10 22:03 UTC, mdulin2 approved these changes
Good CU optimization. 

I checked out the changes in the dependencies changed and it seems fine as well.

2024-07-11 12:48 UTC, johnsaigle requested changes

2024-07-11 12:48 UTC, johnsaigle commented on solana/Cargo.toml
> +or_fun_call = "allow"
[This lint is "allow" by default](https://rust-lang.github.io/rust-clippy/master/index.html#/or_fun_call) so this is redundant. 
Did you want to `"warn"` here instead to enforce usage of the the lazy functions?

2024-07-11 13:45 UTC, a5-pickle commented on solana/Cargo.toml
> +or_fun_call = "allow"
I think I was confused when I read that doc. Changed it to warn here: https://github.com/wormhole-foundation/example-liquidity-layer/pull/191/commits/e8b9fbe419593ec5c057b49f0fd44a1d96f90ea7

2024-07-11 14:42 UTC, johnsaigle approved these changes

2024-08-09 18:02 UTC, gator-boi approved these changes

2024-08-09 18:21 UTC, merged